import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import { useState } from "react";

const Home = () => {
  const { data: session, status } = useSession();
  const [message, setMessage] = useState("");
  const ctx = trpc.useContext();
  const guestbook = trpc.guestbook.postMessage.useMutation({
    onMutate: () => {
      ctx.guestbook.getAll.cancel();

      const optimisticUpdate = ctx.guestbook.getAll.getData();

      ctx.guestbook.getAll.setData(optimisticUpdate);
    },
    onSettled: () => {
      ctx.guestbook.getAll.invalidate();
    },
  });

  if (status === "loading") {
    return <main className="flex flex-col items-center pt-4">Loading...</main>;
  }

  return (
    <>
      <Head>
        <title>T3 Budget</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <h1 className="pt-4 text-3xl">Guestbook</h1>
        <p>
          Tutorial for <code>create-t3-app</code>
        </p>

        <div className="pt-10">
          {session ? (
            <div>
              <p>hi {session.user?.name}</p>

              <button onClick={() => signOut()}>Logout</button>
              <div className="pt-6">
                <form
                  className="flex gap-2"
                  onSubmit={(event) => {
                    event.preventDefault();

                    guestbook.mutate({message})

                    setMessage("");
                  }}
                >
                  <input
                    type="text"
                    value={message}
                    placeholder="Your message..."
                    maxLength={100}
                    onChange={(event) => setMessage(event.target.value)}
                    className="rounded-md border-2 border-zinc-800 bg-neutral-900 px-4 py-2 focus:outline-none"
                  />
                  <button
                    type="submit"
                    className="rounded-md border-2 border-zinc-800 p-2 focus:outline-none"
                  >
                    Submit
                  </button>
                </form>
              </div>
            </div>
          ) : (
            <div>
              <button onClick={() => signIn()}>
                Login
              </button>
            </div>
          )}
          <div className="pt-10" />
          <Messages />
        </div>
      </main>
    </>
  );
};

const Messages = () => {
  const { data: messages, isLoading } = trpc.guestbook.getAll.useQuery();

  if (isLoading) return <div>Fetching messages...</div>;

  return (
    <div className="flex flex-col gap-4">
      {messages?.map((msg, index) => {
        return (
          <div key={index}>
            <p>{msg.message}</p>
            <span>- {msg.name}</span>
          </div>
        );
      })}
    </div>
  );
};

export default Home;
